[[redirects]]
  from = "http://beta.justfix.nyc/*"
  to = "https://www.justfix.nyc"
  status = 301
  force = true

[[redirects]]
  from = "https://beta.justfix.nyc/*"
  to = "https://www.justfix.nyc"
  status = 301
  force = true

[[redirects]]
  from = "http://findhelp.justfix.nyc/*"
  to = "https://www.justfix.nyc"
  status = 301
  force = true

[[redirects]]
  from = "https://findhelp.justfix.nyc/*"
  to = "https://www.justfix.nyc"
  status = 301
  force = true

[[redirects]]
  from = "https://justfix.org/*"
  to = "https://www.justfix.nyc/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://www.justfix.org/*"
  to = "https://www.justfix.nyc/:splat"
  status = 302
  force = true
