[[redirects]]
  from = "http://beta.justfix.nyc/*"
  to = "https://www.justfix.org"
  status = 301
  force = true

[[redirects]]
  from = "https://beta.justfix.nyc/*"
  to = "https://www.justfix.org"
  status = 301
  force = true

[[redirects]]
  from = "http://findhelp.justfix.nyc/*"
  to = "https://www.justfix.org"
  status = 301
  force = true

[[redirects]]
  from = "https://findhelp.justfix.nyc/*"
  to = "https://www.justfix.org"
  status = 301
  force = true

[[redirects]]
  from = "https://justfix.nyc/*"
  to = "https://www.justfix.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.justfix.nyc/*"
  to = "https://www.justfix.org/:splat"
  status = 301
  force = true
