on:
  schedule:
  - cron: "0 5 1 * *"
  workflow_dispatch:

jobs:
  find_dead_links:
    runs-on: ubuntu-latest
    name: Deadlink crawler
    steps:
      - name: Scan learning center
        uses: JustFixNYC/deadlink-crawler@v2.1
        with:
          site-url: "https://www.justfix.org"
          token: ${{ secrets.GITHUB_TOKEN }}